/// Public entry point for the Sewlio Rust engine bindings.
///
/// `lib/src/rust/` is generated by `flutter_rust_bridge_codegen generate`
/// (run `make gen`). Call [initEngine] once at startup before using any API.
library studio_bindings;

export 'src/rust/api/simple.dart';
export 'src/rust/frb_generated.dart' show RustLib;

import 'src/rust/frb_generated.dart';

/// Loads and initializes the Rust engine. Idempotent per isolate.
Future<void> initEngine() => RustLib.init();
