// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Engine version string. Used by the Flutter app to prove the FFI round trip.
/// `sync` so Dart sees a plain `String` (trivial getter, no need for an isolate).
String appVersion() => RustLib.instance.api.crateApiSimpleAppVersion();

/// Distance in millimeters between two points — exercises the geometry domain
/// across the boundary. Placeholder; the real geometry API is command-driven.
double distance(
        {required double x1,
        required double y1,
        required double x2,
        required double y2}) =>
    RustLib.instance.api.crateApiSimpleDistance(x1: x1, y1: y1, x2: x2, y2: y2);
